PROJECT_NAME := check_msc_leds
COMPONENT_ADD_LDFLAGS+= -l lib/libesp_wakenet.a
LIBS+= vad esp_wakenet nn_model_alexa_wn3
include $(ADF_PATH)/project.mk
COMPONENT_ADD_LDFLAGS+= -l lib/libesp_wakenet.a

